FROM resin/%%RESIN_MACHINE_NAME%%-python
MAINTAINER Kimmo Huoman <kipenroskaposti@gmail.com>

RUN apt-get update && apt-get install -yq wget && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

RUN wget -O /tmp/influxdb_0.11.0-1_armhf.deb https://s3.amazonaws.com/influxdb/influxdb_0.11.0-1_armhf.deb && \
    dpkg -i /tmp/influxdb_0.11.0-1_armhf.deb && rm /tmp/influxdb_0.11.0-1_armhf.deb

COPY start.sh /start.sh

ENV INITSYSTEM on
CMD ["bash", "/start.sh"]
